### ISSUE TITLE
User can surpersede the protection of an API by using the same host

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#107]
On cluster-wide deployments of Authorino, i.e. where the Authorino controller watches CRs and Secrets defined across all the cluster rather than in a single namespace, a user with permissions to create Authorino `Service` custom resources can define an API protection listing amongst the `hosts` a host already taken by a different `Service` CR. The Authorino cluster-wide instance that reconciles the newly created CR, will update the cache of auth configs replacing the entry previously taken by the formerly created CR with the auth config stated in the new CR.

### Steps to reproduce

1. Deploy Authorino (cluster-wide)
2. Create an Authorino `Service` CR `x` that includes a host, e.g., `abc.api`
3. Sets Envoy to filter traffic sent to `abc.api` using the Authorino instance as external authorization service
4. Create another Authorino `Service` CR `y`, with a different auth spec (e.g. different identity sources, diff authz policies), but that also includes the host `abc.api`
5. Sends request to `abc.api` and verifies that Authorino `Service` CR `y` was enforced rather than Authorino `Service` CR `x`

### Expected behavior

Authorino should enforce some protection against host collision. E.g. `Service` CRs including host names already taken could be rejected. Perhaps this could be some policy enforced only when different namespaces are involved, as a way to protect user definition from the actions of other users in other user spaces.

#### Example

Consider the following resources:

```yaml
# authorino controller deployed cluster-wide in the `system` namespace
apiVersion: v1
kind: Pod
metadata:
  namespace: system
  name: authorino-controller-1
```

```yaml
# authorino CR `foo` declared in the `x` namespace using host `example.com`
apiVersion: config.authorino.3scale.net/v1beta1
kind: Service
metadata:
  namespace: x
  name: foo
spec:
  hosts:
    - example.com
```

```yaml
# authorino CR `bar` declared in the `y` namespace using host `example.com`
apiVersion: config.authorino.3scale.net/v1beta1
kind: Service
metadata:
  namespace: y
  name: bar
spec:
  hosts:
    - example.com
```

Then (in order):
1. User applies `x/foo` which is **accepted** by the Authorino controller that caches `example.com → x/foo`
2. User applies `y/bar` which is **rejected** by the Authorino controller (otherwise, the owner of `y/bar` would take control over the protection for `example.com`)

#### Problems that may still arise from the proposed approach (based on the example above)

**Problem #&#8203;1:** What if `y/bar` is the legit owner of `example.com`?

This is not an enormous problem because, in order for Authorino to apply the protection over `example.com`, requests to this host must be proxied to Authorino which can only be set by the legit owner of the ingress route.

The only actual problem here is the locking of a host with a stale `Service` config. In case of host collision, the illegitimate holder of a host with a stale `Service` config will have to be requested to release the lock.

**Problem #&#8203;2:** What if instance A of Authorino caches `x/foo` and instance B of Authorino caches `y/bar` in a race condition?

This lead to an inconsistent state where each instance of Authorino knows about a different protection to apply over `example.com`, and the outcome of requests to the protected API is random, as we cannot cannot assume about the order of reconciliation.

A possible solution could be implementing a **centralised cache** although that would introduce a bottleneck. Another possible solution could be through **syncing the cache** across Authorino instances → hard to implement and no actual guarantee of a consistent state.

> Refer to #105 for a discussion about problems in Authorino related to cache reconciliation under multiple instances of the external authorization service and leader election enabled.

**Problem #&#8203;3:** Depending on how Authorino "rejects" a `Service` resource (as for restrictions of the OPerator SDK), this might only mean that the corresponding spec will not be reconciled (i.e. it will not be added to the cache), however the `Service` resource might still be accepted by the API server and remain in the data plane (without status).

> Check out Kubernetes [**ValidatingAdmissionWebhook**](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook) to prevent that.
