### ISSUE TITLE
Configurable evaluator response strategies for the phases of the auth pipeline

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#112]
Authorino implements 3 so-called "strategies" for the 3 first phases of auth pipeline (wristband phase excluded). These strategies are:
- _at least one_ of the concurrent evaluators of the phase must resolve (`at-least-one`);
- _any_ of the concurrent evaluators of the phase must resolve (`any`);
- _all_ of the concurrent evaluators of the phase must evaluate (`all`).

These strategies currently map one-to-one with the first 3 phases of Authorino's auth pipeline, respectively: **identity** phase, **metadata** phase and **authorization** phase. I.e.,
- if more than one identity source is specified, the supplied token or credential must always be validated with _at least one_ the sources (i.e., `at-least-one`);
- if more than one external source of metadata is specified, _any_ number of them (from none, to all of them) can return a proper value and still Authorino will trigger the next phase (authorization) regardless (i.e., `any`);
- if more than one authorization policy is specified, _all_ of them must grant access, otherwise access will be denied altogether (i.e., `all`).

This issue is a request to make how the 3 strategies map to the phases configurable, with the default strategies still falling back to the ones currently enforced.

#### Example for a possible implementation

```yaml
apiVersion: config.authorino.3scale.net/v1beta1
kind: Service
metadata:
  name: my-api-protection-1
spec:
  hosts:
    - myapi.io
  identity:
    - name: auth-server-1
      oidc:
        endpoint: https://auth-server-1/auth
    - name: auth-server-2
      oidc:
        endpoint: https://auth-server-2/auth
  metadata:
    - name: semaphore-1
      http:
        method: GET
        sharedSecretRef:
          name: myapi-protection-metadata-secrets
          key: semaphore-1-shared-auth
    - name: semaphore-2
      http:
        method: GET
        sharedSecretRef:
          name: myapi-protection-metadata-secrets
          key: sempahore-2-shared-auth
  authorization:
    - name: authz-policy-1
      json:
        rules:
          - selector: auth.metadata.semaphore-1.color
            operator: eq
            value: green
          - selector: auth.metadata.semaphore-2.color
            operator: eq
            value: green
          - selector: auth.identity.role
            operator: eq
            value: restricted-user
    - name: authz-policy-1
      opa:
        inlineRego: |
          semaphore1 { input.auth.metadata.semaphore-1.color == "red" }
          semaphore2 { input.auth.metadata.semaphore-2.color == "red" }
          sunday { time.weekday(time.now_ns()) == "Sunday" }
          allow { not semaphore1; not semaphore2; sunday }
  identityStrategy: any
  metadataStrategy: all
  authorizationStrategy: atLeastOne
```

The example above would be for a case where all the default strategies are overridden as follows:
- _any_ of the identity sources can help verifying the identity (including none, i.e., authenticating is optional);
- _all_ metadata sources must respond with data;
- _at least one_ of the authorization policies must grant access – i.e., either the user was authenticated and has the "restricted-user" role, or it's a Sunday; in both cases semaphore 1's and semaphore 2's colors can neither be "red".

#### Special considerations

The cases for configurable strategies in the **metadata** and in  the **authorization** phases are less probably needed than the one for the **identity** phase, due to the existing options to represent conditionals in Authorino authorization policies (both, in OPA policies and in JSON  pattern-matching policies). The configurability of the strategies would nonetheless provide another way to describe the authorization logic, at the very least improving readability in some cases.

Another thing to take into account is what happens when, in the metadata phase, the chose strategy fails (e.g. `atLeastOne` or `all` enforced, but none of the sources respond)? Should Authorino reject the request as DENIED? Would this virtually be promoting the metadata sources to potential external authorizers?
