### ISSUE TITLE
HTTP external metadata parameters in the body of the request

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#151]
Currently, Authorino's HTTP external metadata feature allows sending GET and POST requests to an external service in the metadata phase of the Auth Pipeline. The endpoint of the external service accepts placeholders for variable data fetched from the Authorization JSON. E.g.:

```yaml
metadata:
  name: my-ext-metadata-source
  http:
    endpoint: http://talker-api.authorino.svc.cluster.local:3000/authz?requested_path={context.request.http.path}
```

However, one cannot send such variable values in the request body, which in some cases would be more suitable (and safer), especially when the request method is POST.

This issue is an RFE to add a proper configuration option to specify request parameters other than endpoint placeholders. E.g.:

```yaml
metadata:
  name: my-ext-metadata-source
  http:
    endpoint: http://talker-api.authorino.svc.cluster.local:3000/authz?other_param={still.supported}
    parameters:
      - name: requested_path
        valueFrom: context.request.http.path
      - name: fixed_param
        value: fixed value
```

Perhaps, this alternative, allowing to drop support for the placeholders in the endpoint altogether:

```yaml
metadata:
  name: my-ext-metadata-source
  http:
    endpoint: http://talker-api.authorino.svc.cluster.local:3000/authz
    parameters:
      - name: requested_path
        valueFrom: context.request.http.path
        location: body
      - name: fixed_param
        value: fixed value
        location: body
      - name: other_param
        value: some value
        location: queryString
```

**Comment by miguelsorianod** [comment]
Hi,

Probably having both options would be good. Some APIs provide the configurability using query params in the URL whereas others expect the content in the body (and some others accept both). I understand that for the body you intend to support JSON input then? has it been considered to allow providing an arbitrary body to support other formats?

**Comment by guicassolato** [comment]
> Probably having both options would be good. 

Sure.

> I understand that for the body you intend to support JSON input then? has it been considered to allow providing an arbitrary body to support other formats?

We could support a `contentType` option; whenever it's `application/json`, Authorino builds a JSON object out of `parameters` and send it in the body.

**Comment by guicassolato** [comment]
I've just realised `POST` requests by the HTTP metadata feature already sends the entire Authorization JSON in the payload:
https://github.com/Kuadrant/authorino/blob/902bd7c15faefa3d34e9580380ac7b119f166bd7/pkg/config/metadata/generic_http.go#L37

(I guess 4 months is too long ago for my 🐟 memory to remember.)

Anyway, the issue still makes sense IMO. To avoid leaking sensitive data in this request and yet introducing support for the content-type option, I will propose the following, without breaking the existing API:

```yaml
metadata:
  name: my-ext-metadata-source
  http:
    endpoint: http://talker-api.authorino.svc.cluster.local:3000/authz?other_param={still.supported}
    contentType: application/json # other options being: 'text/plain' and 'application/x-www-form-urlencoded'
    bodyParameters:
      - name: requested_path
        valueFrom:
          authJSON: context.request.http.path
      - name: fixed_param
        value: fixed value
```
