### ISSUE TITLE
How to access the namespace of the service account in conditions/rules/opa?

### ISSUE THREAD

**Issue by GrahamDumpleton** [Kuadrant/authorino#152]
This is perhaps more a question of how to do something rather than bug/feature request but you don't have a category for that. :-)

I am trying to create an example to test with based on a configuration in this video.

* https://youtu.be/JPxZaa3pxcw?t=2954

That video has an `authJSON` value which uses `auth.identity.serviceaccount.name`.

If I try and validate that works by using:

```
  identity:
    - name: same-k8s-server-users
      kubernetes:
        audiences:
          - talker
      extendedProperties:
      - name: "myname"
        valueFrom:
          authJSON: "auth.identity.serviceaccount.name"
```

then in the logging from the authorino process it shows:

```
2021-09-28T06:50:14.399Z	INFO	Authorino.AuthPipeline	Identity	{"config": {"Name":"same-k8s-server-users","ExtendedProperties":[{"Name":"myns","Value":{"Static":null,"Pattern":"auth.identity.serviceaccount.name"}}],"OAuth2":null,"OIDC":null,"MTLS":null,"HMAC":null,"APIKey":null,"KubernetesAuth":{"AuthCredentials":{"KeySelector":"Bearer","In":"authorization_header"}}}, "authObj": {"aud":["talker"],"exp":1632812295,"iat":1632811695,"iss":"https://kubernetes.default.svc.cluster.local","kubernetes.io":{"namespace":"authorino","serviceaccount":{"name":"api-consumer","uid":"f40c2ef6-1da9-448b-a243-b06c9099c283"}},"myname":null,"nbf":1632811695,"sub":"system:serviceaccount:authorino:api-consumer"}}
```

So `myname` appears as `null` and not the service account name as would expect.

The issue seems to be that the `serviceaccount` details is actually nested under `kubernetes.io` as a dictionary and if that is correct that would imply what the video shows can't work. Problem is I can't work out what syntax should be allowed in `authJSON` to do the equivalent of:

```
auth.identity["kubernetes.io"].serviceaccount.name
```

even if that is supported.

Anyway, I started with the example from that video first. What I actually want to access is the `namespace` of the service account, which if `kubernetes.io` didn't exist, and based on what video showed might work for service account name may have been done by accessing:

```
auth.identity.namespace
```

What I ultimately what to be able to use the namespace value for is in conditions/rules so I can control access to sub paths of a API service based on the namespace the service account is located in.

More specifically, I want to see whether authorino can control things in a way equivalent of what the OpenShift image registry sort of does in respect of only permitting access to notional projects in the image registry based on the service account namespace.

In the case of OpenShift it is a bit more complicated as it also entails have appropriate RBAC resource/verbs as well, but trying at least to base it on namespace.

So the idea would be that by default access to image registry would be blocked.

If however path is `/v2/<namespace>/*` then only service account with matching namespace would have `GET`, `PUSH`, `PUT`, `DELETE` etc as necessary.

Main question therefore is how do you reference the service account namespace? With tests I can't seem to get it to work based on guess about what might use by seeing the video and looking at authorino logs and how data is.

If you have any guidance/examples on using the namespace of the service account in conditions/rules/opa to fulfill what am trying to do that also would be most useful.

As secondary question, have you had any thoughts of authorino being able to hook into `SubjectAccessReview` so one could actually control access to things via service token using Kubernetes RBAC (resources/verbs). This would allow the additional level of control similar to what `registry-viewer` and `registry-editor` roles in OpenShift provide using underlying custom resources/verbs related to registry access.

As to the version I am testing with, I used the tutorial to get started, fixing the cluster role binding issue with `authorino-proxy-role`. The deployment of authorino says it is using `quay.io/3scale/authorino:latest`.

**Comment by guicassolato** [comment]
Hi @GrahamDumpleton. Thanks for your interest in Authorino 🙂

Your first question is an easy one. The patterns to refer to values of the Authorization JSON in a `valueFrom` field, `selector` field of a JSON pattern-matching authorization rule, or placeholder of an HTTP metadata endpoint are based on https://github.com/tidwall/gjson. If the name of the JSON property contains a dot (as in `kubernetes.io`), you need to escape the dot with a backslash. There's a catch though. The backslash itself needs to be acknowledged, so it's actually a double escaping.

Your pattern to access the namespace of SA should look like the following:

```yaml
valueFrom:
  authJSON: "auth.identity.kubernetes\\.io.namespace"
```

The only exception to the above is when you traverse the Authorization JSON inside of an OPA policy. In this case Rego's syntax prevails. E.g.:

```
namespace := input.auth.identity["kubernetes.io"].namespace
```

Here's a complete example using both syntaxes above in an `AuthConfig` and roughly trying to address the use case you've described:

```yaml
apiVersion: authorino.3scale.net/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
    - talker-api

  identity:
    - name: same-k8s-server-users
      kubernetes:
        audiences:
          - talker
      extendedProperties:
        - name: "myname"
          valueFrom:
            authJSON: "auth.identity.serviceaccount.name"
        - name: "ns"
          valueFrom:
            authJSON: "auth.identity.kubernetes\\.io.namespace"

  authorization:
    - name: only-namespaces-with-foo-prefix-are-allowed
      json:
        rules:
          - selector: "auth.identity.kubernetes\\.io.namespace" # or simply "auth.identity.ns" since it was normalized
            operator: matches
            value: "foo-.*"

    - name: only-matching-namespaces
      opa:
        inlineRego: |
          http_request = input.context.request.http
          http_method = http_request.method
          requested_path = trim_right(http_request.path, "/")
          path_sections = split(trim_left(requested_path, "/"), "/")
          same_namespace = path_sections[1] == input.auth.identity["kubernetes.io"].namespace # or simply "input.auth.identity.ns" since it was normalized
          allowed_methods = ["GET", "PUSH", "PUT", "DELETE"]
          allow { same_namespace; allowed_methods[_] == http_method }
```

As for your second question, about `SubjectAccessReview`. Yes, we have thought about adding support for it in the authorization phase. We would call the feature in Authorino "Kubernetes Authorization" – an obvious name after the already supported "Kubernetes Authentication", based on `TokenReview`.

The reason why we haven't done it yet was just because one who's interested in the bare combination `TokenReview` + `SubjectAccessReview` already has a solution for that. This is exactly what [kube-rbac-proxy](gcr.io/kubebuilder/kube-rbac-proxy) is: proxy + `TokenReview` + `SubjectAccessReview`. So we have decided to focus on other features fir, like OPA, OIDC, etc.

However, now that you've mentioned it, and considering one might still be interested in combining those Kubernetes-provided auth features with other features of Authorino (e.g. OPA, JSON authz, metadata fetching, wristband tokens, etc), I'll make sure to open an issue and put `SubjectAccessReview` in our roadmap.

It's an easy implementation anyway and PRs are welcome 🙂 Anybody interested in contributing can find some "inspiration" in https://github.com/brancz/kube-rbac-proxy/blob/master/pkg/authz/auth.go.

**Comment by GrahamDumpleton** [comment]
From memory authorino was more attractive than kube-rbac-proxy as for one use case I needed to handle multiple notional upstreams through same proxy as the destination pod could handle virtual hosts. Also authorino allows one to stack other auth methods. Thus in addition to service account token access, could have an API token as well, or something else. So for image registry case, service accounts may have read only access to whole registry and use an API token account for write access.

Anyway, thanks for all the information. I will play some more tomorrow.

**Comment by GrahamDumpleton** [comment]
Got another question related to that example configuration you provided.

What if I had multiple `identity` options that could match, eg.,

```
  identity:
    - name: api-key-users
      apiKey:
        labelSelectors:
          authorino.3scale.net/managed-by: authorino
          group: friends
    - name: same-k8s-server-users
      kubernetes: {}
```

The `authorization` checks though apply whatever `identity` matches and as I understand it they all need to succeed.

I might want a situation where if someone comes in via an api key that they should be allowed to immediately do anything. It is only if came in via Kube service account that would want to apply the additional authorization checks. If don't have a way to say which authorization applies to which identity source, then the checks relying on service account would fail always when applied to api key path. Although I guess I could fudge data using extended properties added to distinguish in that case which would be okay for opa scripted check, but probably not so for other checks like SubjectAccessReview where couldn't probably fudge things so would work.

Is there are way of saying that authorization checks should only be applied to specific named identity source, or is this mixing of identity sources a bad idea and I should instead be exposing the service under multiple host names and thus have multiple `AuthConfig` to keep them separate?
