### ISSUE TITLE
User-defined headers to HTTP external metadata request

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#183]
Authorino does not allow users to freely customize the headers of the HTTP request sent by the [generic HTTP external metadata](https://github.com/Kuadrant/authorino/blob/main/docs/architecture.md#external-http-authorization-metadata) feature. Only `Content-Type` and `Authorization` headers can be configured; even so, the former is limited to a couple values used to format the payload, and the latter can be set exclusively from a `sharedSecretRef` option.

An extension of the API changing that could possibly support:

```yaml
metadata:
  - name: ams-current-account
    http:
      endpoint: https://metadata-source.svc.cluster.local
      headers:
        - name: X-Custom-Header
          value: some-value
        - name: Authorization
          valueFrom:
            authJSON: context.request.http.headers.authorization # carries the same authentication provided in the original request to the protected service, to the request to the external metadata
      credentials:
        in: authorization_header
        keySelector: Bearer
      sharedSecretRef:
        name:  my-secret
        key: some-key
```

**Questions and thoughts based on the example above:**
1. Does `metadata.http.credentials.in='authorization_header'` override the custom header or add a second `Authorization` header?
    _A:_ My guess is that it would override the custom header.

2. If `metadata.http.credentials.in` is set to anything other than `authorization_header`, would it be virtually like providing 2 authentication values?
    _A:_ I guess so.

3. If `metadata.http.sharedSecretRef` had been omitted, then `metadata.http.credentials` would have no meaning. Would a user find this weird because a custom `Authorization` header has been set but `credentials` below changes nothing?
    _A:_ My guess is that this is not a problem, since it is how `credentials` and `sharedSecretRef` already work together today and custom headers would be a new thing, not necessarily meant only to customize the `Authorization` header.

4. Would users expect to be able to custom set the `Authorization` header from a secret but by adding it to `metadata.http.headers`?
    _A:_ Maybe yes, but there is already a way to set `Authorization` header and even custom headers from a secret for the purpose of authentication. Users should use that in this case.

5. Would users expect to set authentication `valueFrom.authJSON` into a credential vector other than the `Authorization` header (e.g. as a cookie).
    _A:_ Out of scope as this is about custom headers, not about enhancing authentication config.
