### ISSUE TITLE
Evaluators within a phase always trigger in parallel

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#184]
From the [docs](https://github.com/Kuadrant/authorino/blob/main/docs/architecture.md#the-auth-pipeline):

> Each phase [of the Auth Pipeline] is sequential to the other [...], while the evaluators within each phase are triggered concurrently.

This makes impossible to write configs that depend or somehow affect other configs in the same phase of the auth pipeline.

A practical example would be an external metadata config that requires another metadata config to be resolved first, say, e.g., because the object returned by the first metadata source is used to set a parameter or URL of the second metadata request.

**A possible solution to this limitation:** extend the API with a field to set the sequence/priority of execution of the evaluators within the phase.

Say the evaluator configs would accept a field `priority: integer`. In each phase of the Auth Pipeline, Authorino would trigger in parallel all the evaluators of same `priority` (starting with the default priority 0), then move to the next block of `priority`, and to the next, until there's no evaluator/priority left. Since every time an evaluator is called, it gets the latest state of the Authorization JSON, evaluators of priority _N_ will count on objects appended to the Authorization JSON during priority _N-1_.

This behaviour applied to the identity verification phase could be used, e.g., to tell Authorino to _"first try to validate the access token with this/these identity sources (say, priority 0) and, if none of them accepts the token, then try with these other sources (say, priority 1)"_.

Analogously, applied to authorization evaluators: _"If none of the policies within this first block of policies (prio: 0) denies access, then try this second block (prio: 1)"_.

To external metadata, one could have a config, e.g., to implement master-details requests as such:

```yaml
metadata:
  - name: master
    http:
      endpoint: https://external-metadata-source.io/master # suppose it returns {"id":123, ...}
  - name: details
    http:
      endpoint: https://external-metadata-source.io/details?master_id={auth.metadata.master.id}
      priority: 1
```
