### ISSUE TITLE
Authorino manager `ClusterRole` `manager-role` misses the permission for `TokenReview` and `SubjectAccessReview`

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#185]
Authorino's [`manager-role`](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/install/rbac/role.yaml) `ClusterRole` misses the permission to create `TokenReview` and `SubjectAccessReview` resources, required for the [Kubernetes token verification](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/docs/architecture.md#kubernetes-authentication) and [Kubernetes authorization](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/docs/architecture.md#kubernetes-authorization) features.

This has not been felt as an issue because [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) [defines these permissions](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/install/rbac/auth_proxy_role.yaml) and, when [deployed as a sidecar of Authorino](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/deploy/base/kustomization.yaml#L27), it ends up [binding the same `ServiceAccount` to the role](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/deploy/overlays/cluster-wide-notls/kustomization.yaml#L7).

However, these things should not be mixed up together, or an eventual removal of the sidecar patch could (would!) cause authn/authz features of Authorino to crash. Authorino's `manager-role` should include these permissions regardless:

```yaml
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
```
