### ISSUE TITLE
Builtin OPA to support integration with OPA's Management interface

### ISSUE THREAD

**Issue by tayyabjamadar** [Kuadrant/authorino#195]
**Is your feature request related to some problem you are facing? Please describe that problem here.**

:- Want to integrate builtin OPA with Authorino in such a way that fetching the policy bundles from a remote HTTP server and streaming logs to the same is possible. Basically, want to integrate the builtin OPA with the Management Interface as mentioned [here](https://www.openpolicyagent.org/docs/latest/integration/#:~:text=This%20page%20focuses,performance%20and%20errors.) in OPA's docs. 

Currently builtin OPA only supports inline rego and policies from the external OPA policy registry.

OPA integration is accomplished in other similar tools via an External Auth plugin that connects with the Opa-envoy service, and opa-envoy supports the APIs mentioned on the above doc. But since we have builtin OPA here I think supporting the management interface APIs would be great.

**Describe alternatives you've considered**
:- This can also be achieved if Authorino supports Ext Auth to the grpc(similar like envoy) or http.(But I guess Ext Auth is under analysis)

Did you already reject some other solutions, for some particular reasons?
If you can share those here, you'll be saving everyone's time when someone has thought of the same solution you've already rejected.

:- None rejected.

**Comment by guicassolato** [comment]
Hi @tayyabjamadar

You should be able to fetch Rego policies from a remote HTTP registry with Authorino. The feature was introduced in #144 and it's available since Authorino v0.5.0.

It's right [here](https://github.com/Kuadrant/authorino/blob/54b9ec6cf3575e777c5a859221995db825dee02b/install/crd/authorino.3scale.net_authconfigs.yaml#L371) in the spec. Sorry if you couldn't find it in the docs. We're right now working on [enhancing](https://github.com/Kuadrant/authorino/pull/180) them.

Here's an example of an `AuthConfig` using OPA external policy registry:

```yaml
apiVersion: authorino.3scale.net/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
  - talker-api-authorino.127.0.0.1.nip.io
  identity:
  - name: friends
    apiKey:
      labelSelectors:
        group: friends
    credentials:
      in: authorization_header
      keySelector: APIKEY
  authorization:
  - name: read-only-outside
    opa:
      externalRegistry:
        endpoint: https://my-opa-server/v1/policies/policy-id
        sharedSecretRef: # optional - name of k8s secret that stores the credentials to authenticate with the policy registry API
          name: my-secret
          key: secret-key-name
        credentials: # optional - where the authentication secret flies in the request
          in: authorization_header
          keySelector: Bearer
```

You can get some extra info by running on a cluster where the Authorino CRDs are installed:

```
kubectl explain services.spec.authorization.opa.externalRegistry --api-version='config.authorino.3scale.net/v1beta1'
```

And here's a user guide with an example for trying Authorino with OPA: https://github.com/Kuadrant/authorino/blob/docs-restructuring/docs/user-guides/opa-authorization.md (adapt the `AuthConfig` as above; link may expire once the PR is merged and the branch is deleted.)
