### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#205]
Authorino's [JSON pattern-matching authz](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#json-pattern-matching-authorization-rules-authorizationjson) and [K8s SubjectAccessReview-based authz](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#kubernetes-subjectaccessreview-authorizationkubernetes) both define a field called `conditions` that allows to specify rules for Authorino to decide when to apply or to skip that particular policy. The 3rd type of authz supported by Authorino, which is [OPA authz](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#open-policy-agent-opa-rego-policies-authorizationopa), does not define `conditions` because one could easily model the same logic in Rego.

Perhaps `conditions` could be brought to all evaluator configs of all phases (identity, metadata, authorization and dynamic response), and maybe even to top level of the `AuthConfig` as a whole.

After the lookup – which shall continue to be based on the host at first –, the config as a whole as well as parts of it can be decided to be either enforced or skipped based on those multiple `conditions` fields, specified at the top level and/or at the level of each evaluator.

With `conditions` defined at the top level of the `AuthConfig` (right after the lookup), maybe each condition could be given a unique name. In the other `conditions` fields defined at each specific evaluator (e.g. the one for a particular authn method to be evaluated, or for a particular metadata config), a named top-level condition could be referenced, thus avoiding repetition of rules whenever a same set can be reused in multiple places. There is also a potential for inheritance here.

The good thing of using `conditions` is that it counts with the entire Authorization JSON as input, meaning matching rules could be based on path, on any attribute of the HTTP request or even on attributes of objects appended to the Authorization JSON in other phases (e.g. only fetching some particular metadata when a certain authn method was used). Plus, the cost of implementation of `conditions` as described here is low since the functionality already exists.

Maybe in the future, eventually replacing the lookup based on host strictly, with the “top-level conditions” could be a no-brainer, assuming ways to solve the issues of the lookup complexity and preventing overlapping `AuthConfig` (aka "[avoiding host name collision](https://github.com/Kuadrant/authorino/blob/main/docs/architecture.md#avoiding-host-name-collision)") can be figured out. This could be a way to address #171 (on steroids!)

----

**Example of `AuthConfig` using conditions:**

```yaml
apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: my-api-protection
spec:
  hosts:
  - my-api.io

  conditions:
  - selector: context.request.http.path
    operator: neq
    value: /status

  identity:
  - name: idp-users
    oidc:
      endpoint: https://my-idp/auth/realms/my-realm
  - name: admins
    apiKey:
      labelSelectors:
        authorino.kuadrant.io/managed-by: authorino
      credentials:
        in: authorization_header
        keySelector: APIKEY
    conditions:
    - selector: context.request.http.path
      operator: matches
      value: /admin(/.*))$
    - selector: context.request.http.headers.authorization
      operator: matches
      value: APIKEY .+
    extendedProperties:
    - name: username
      valueFrom:
        authJSON: auth.identity.metadata.annotations.username
    - name: roles
      value: ["admin"]

  metadata:
  - name: resource-metadata
    http:
      endpoint: http://metadata-source/pets/{context.request.http.path.@extract:{"sep":"/","pos":2}}/meta
      method: GET
    conditions:
    - selector: context.request.http.path
      operator: matches
      value: /pets/\d+(/.*))$  

  authorization:
  - name: owner-policy
    opa:
      inlineRego: |
        allow { input.auth.identity.username == input.metadata["resource-metadata"].owner }
    conditions:
    - selector: context.request.http.path
      operator: matches
      value: /pets/\d+(/.*))$
  - name: admin-role-required
    json: # now reduced only to what's currently the 'rules' part of the spec, since 'conditions' moved to the upper level
    - selector: auth.identity.roles
      operator: incl
      value: "admin"
    conditions:
    - selector: context.request.http.path
      operator: matches
      value: /admin(/.*))$
```

In the example above:
- Requests to `/status` will not be protected by the `AuthConfig`
- Users trying to access paths under `/admin` can _also_ authenticate using API key
- Conditions for `identity[name="admins"]` and `authorization[name="admin-role-required"]` share at least one rule in common – maybe this rule could be defined at the top-level and referenced.
- Conditions for `metadata[name="resource-metadata"]` and `authorization[name="owner-policy"]` are the exactly same – maybe it could be defined at the top-level and referenced.

**Comment by guicassolato** [comment]
An enhanced version of the one in the description, with named conditions that can be referred to avoid repetition:

```yaml
apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: my-api-protection
spec:
  hosts:
  - my-api.io

  namedConditions:
    pets:
    - selector: context.request.http.path
      operator: matches
      value: /pets/\d+(/.*))$  
    admin:
    - selector: context.request.http.path
      operator: matches
      value: /admin(/.*))$

  conditions:
  - selector: context.request.http.path
    operator: neq
    value: /status

  identity:
  - name: idp-users
    oidc:
      endpoint: https://my-idp/auth/realms/my-realm
  - name: admins
    apiKey:
      labelSelectors:
        authorino.kuadrant.io/managed-by: authorino
      credentials:
        in: authorization_header
        keySelector: APIKEY
    conditions:
    - conditionRef: admin
    - selector: context.request.http.headers.authorization
      operator: matches
      value: APIKEY .+
    extendedProperties:
    - name: username
      valueFrom:
        authJSON: auth.identity.metadata.annotations.username
    - name: roles
      value: ["admin"]

  metadata:
  - name: resource-metadata
    http:
      endpoint: http://metadata-source/pets/{context.request.http.path.@extract:{"sep":"/","pos":2}}/meta
      method: GET
    conditions:
    - conditionRef: pets

  authorization:
  - name: owner-policy
    opa:
      inlineRego: |
        allow { input.auth.identity.username == input.metadata["resource-metadata"].owner }
    conditions:
    - conditionRef: pets
  - name: admin-role-required
    json: # now reduced only to what's currently the 'rules' part of the spec, since 'conditions' moved to the upper level
    - selector: auth.identity.roles
      operator: incl
      value: "admin"
    conditions:
    - conditionRef: admin
```
