### ISSUE TITLE
Allow anonymous access

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#217]
Right now, Authorino requires at least one identity evaluator config in the `AuthConfig` or authorization request will fail with a `401 Forbidden`. This is a placeholder for allowing anonymous access to services protected with Authorino.

A possible implementation of such could be by defining a "no-op" identity verification method that always returns a static object `{ "anonymous": true }`.

```yaml
spec:
  identity:
  - name: anonymous
    anonymous: {}
```

One could use the no-op identity config to delegate full auth to OPA:

```yaml
spec:
  identity:
  - name: anonymous
    anonymous: {}
  authorization:
  - name: auth
    opa:
      inlineRego: |
        authn { ... }
        authz { ... }
        allow { authn; authz }
```

Combined with [priorities](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#common-feature-priorities), anonymous access could be set as fallback for other priority authn methods, with possible different authz rules for the different cases. E.g.:

```yaml
spec:
  identity:
  - name: jwt
    oidc: { endpoint: ... }
  - name: anonymous
    anonymous: {}
    priority: 1 # expired token, missing creds, etc, all default to anonymous access
  authorization:
  - name: read-only-access-if-authn-fails
    when:
    - selector: auth.identity.anonymous
      operator: eq
      value: "true"
    json:
      rules:
      - selector: context.request.http.method
        operator: eq
        value: GET
```
