### ISSUE TITLE
AuthConfig lookup based on host + path prefix

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#222]
The AuthConfig reconciler caches and the authz service looks up for an AuthConfig in request-time, using the host names as key (with optional `:port` suffix). An AuthConfig can list multiple host names; each host name will be another key in the map pointing to that AuthConfig.

This lookup mechanism is simple and efficient, relying always in this one piece of info available in the Envoy payload, i.e. the host name. On the other hand, it requires different protected services to have different domain names (e.g. different subdomains), which is not always possible.

In some cases, using a combination of host name and path prefix is preferable to look up for a particular AuthConfig to enforce.

### Discussion

**Related issues**

Supporting host name+path prefix lookups is not the same as the requested in #171, though these requests can be related. Whereas that other issue requests and enhancement of the AuthConfig caching/lookup mechanism to add support for wildcard domains (e.g., AuthConfig lists `*.my.domain`, lookup matches both `foo.my.domain` and `bar.my.domain`), this one is for being able to use as key the host name plus a path prefix (e.g. AuthConfig lists `my.domain/foo`, lookup matches `my.domain/foo*`, but it does not match `my.domain/bar*`).

[`when` conditions](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#common-feature-conditions-when) defined at the upper level of an AuthConfig, introduced by #205, can also be relevant to this request. However, the sematincs is not the same. Conditions are post-lookup, i.e., after using the host name to lookup, Authorino evaluates the conditions to decide whether to effectively enforce the found AuthConfig or not. If the conditions do not match, Authorino returns right away with a `404 Not Found` deny access response and does NOT keep looking for other possible AuthConfig hits.

**Non-trivial implementation**

To maintain _O(1)_ lookup time complexity, unless some very strict rules are enforced regarding what qualifies for a path prefix and that becomes something valid for all AuthConfigs cached by an Authorino instance, supporting the path prefixes in the lookup keys for AuthConfigs is non-trivial.

In request-time, Authorino can only jump straight to a cache entry if it knowns beforehand what to extract from the Envoy payload as the lookup key. As an example, it would not be possible for an AuthConfig to list a lookup key, say, `my.domain/foo` (1-part path prefix `/foo`) and another AuthConfig to use `my.domain/bar/baz` (2-part path prefix `/bar/baz`), and that to a be a detail specified within each AuthConfig. It would have to be always, say, 1-part path prefixes, or always k-part path prefixes, to all AuthConfigs.

If such strict rule cannot be enforced via configuration option for the entire Authorino instance, Authorino would have to go through the entire list of keys to lookup for an AuthConfig, trying to match based on the specific rules specified within each AuthConfig (i.e., for each AuthConfig evaluating a more complex matcher against the Envoy payload), and therefore _O(1)_ lookup could no longer be guaranteed.

Another challenge comes from [preventing collisions](https://github.com/Kuadrant/authorino/blob/main/docs/architecture.md#avoiding-host-name-collision) between AuthConfigs owned by different users (i.e. defined in different K8s namespaces). Straightforward host name-based caching/lookup makes it simple to prevent users from overriding someone else's AuthConfigs. Supporting more complex matchers can pose a serious challenge to that feature of Authorino.

**Next steps**
To move forward with this issue, first we need to decide whether we want to keep _O(1)_ lookup complexity or if that can be broken to favour more complex matchers.

In the latter case, top-level `when` conditions can provide the base for the implementation, either merging somehow inside of the cache lookup or even replacing it entirely (i.e. lookup fully based on top-level `when` conditions and no longer based on the host names). #171 would be achieved naturally.

On the other hand, efficient host name + path prefix lookup can still be achieved with single extraction rule to obtain the lookup key from the Envoy payload, valid for the entire Authorino instance. In this case, the semantics of top-level `when` conditions does not have to change and #171 will have to continue to be discussed separately.

In both cases, special care must be given to preventing AuthConfigs from being overridden by other specs (defined by other users in different namespaces), that could bend the lookup step in a way that deterministic AuthConfig enforcement can no longer be guaranteed – i.e., it becomes subject to chance due to order of overlapping lookup matchers in the cache. This would be unacceptable of course.

**Comment by guicassolato** [comment]
I've been trying a couple things with Envoy, exploring the options that could lead to minimal changes in the AuthConfig lookup, particularly aiming to trying to keep the _O(1)_ complexity.

The use cases in mind were:
1. Wildcard (sub)domains – e.g. an AuthConfig for `pets.com` to cover requests sent to `*.pets.com`; concrete requests will be sent to `dogs.pets.com`, `cats.pets.com`, etc, which is what Authorino would also normally receive in the payload from Envoy
2. Path-based API routing with a common base domain – i.e. multiple APIs, all APIs share the same base domain (e.g. `pets.com`), the path indicates which API the traffic goes to (e.g. `pets.com/dogs`, `pets.com/cats`), each API has its own AuthConfig, all AuthConfigs being served by the same Authorino instance.

I've explored 2 options of each of 2 very different approaches. None of the alternatives so far is great, but it can be a starting point.

### 1st approach - rewriting the host in Envoy before sending the request to Authorino

For use-case 1 (wildcard domains), it's trivial. Rewrite `dogs.pets.com`, `cats.pets.com` or (in general) `*.pets.com` simply as `pets.com` (i.e. discard the subdomain), and we can have an AuthConfig cached for `pets.com` that will work for all subdomains. If you need a more specific AuthConfig to be enforced for, say, `fishes.pets.com`, just don't rewrite this one.

For use-case 2 (path-based routing), rewrite the host originally from `pets.com`, using the information for the path, to a more specific (fake) subdomain that the AuthConfig is associated with, e.g. `pets.com/dogs` becomes `dogs.pets.com`, there's an AuthConfig for `dogs.pets.com`, another one for `cats.pets.com`.

- **PRO:** nothing to change in Authorino
- **CON:** the upstream API may depend on the Host header; changing it is risky and in some cases may require changing the host back, before redirecting the traffic to the upstream; either way, modifying the HTTP request only to accommodate for restrictions of the authz service feels wrong

At first, I tried using Envoy's route config [`host_rewrite_path_regex`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-host-rewrite-path-regex) option.

Example for use-case 2 (path-based routing):

```yaml
route_config:
  virtual_hosts:
  - name: pets
    domains:
    - pets.com
    routes:
    - match:
        prefix: /
      route:
        cluster: pets
      host_rewrite_path_regex:
        pattern:
          google_re2: {}
          regex: "^/([^/]+)(/.+)?$"
        substitution: \1.pets.com
```

However, this doesn't work. Envoy will only change the host _after_ the external authorization filter.

I also tried using Lua filters:

```yaml
http_filters:
- name: envoy.filters.http.lua
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
    inline_code: |
      function envoy_on_request(request_handle)
        request_handle:headers():replace(":authority", string.match(request_handle:headers():get(":path"), '[^/]+')..".pets.com")
      end
- name: envoy.filters.http.ext_authz
  typed_config: {…}
```

This one works.

### 2nd approach - picking the AuthConfig in Envoy

If Envoy could pass the name of the AuthConfig in the payload to the ext-authz /Check request, Authorino could then bypass the lookup in those cases and jump straight to enforcing that AuthConfig.

- **PRO:** no messing up with the original HTTP request; same implementation in Envoy solves for both use cases
- **CON:** requires changes in Authorino; Envoy needs to be aware of the name of the AuthConfig (a pretty big con IMHO)

For this approach, we can either use Envoy ext-authz's [`check_settings.context_extensions`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html#extensions-filters-http-ext-authz-v3-checksettings) (it is a per route configuration option) or a trick with [Set-Metadata HTTP filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/set_metadata_filter#config-http-filters-set-metadata).

Example using `context_extensions`:

```yaml
route_config:
  name: local_route
  virtual_hosts:
  - name: pets_api
    domains: ['pets.com']
    typed_per_filter_config:
      envoy.filters.http.ext_authz:
        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
        check_settings:
          context_extensions:
            authconfig: default/pets-authconfig
```

Example with Set-Metadata filter:

```yaml
http_filters:
- name: envoy.filters.http.set_metadata
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.set_metadata.v3.Config
    metadata_namespace: authorino
    value:
      authconfig: "default/pets-authconfig"
- name: envoy.filters.http.ext_authz
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
    transport_api_version: V3
    failure_mode_allow: false
    include_peer_certificate: true
    metadata_context_namespaces:
    - authorino
    grpc_service:
      envoy_grpc:
        cluster_name: external_auth
      timeout: 1s
```

### Intermediary approach: passing the host-based lookup key in the metadata

Something in the middle between 1st and 2nd approaches above would be making Envoy to pass the host-based AuthConfig lookup key in the metadata.

- **PRO:** no messing up with the original HTTP request; Envoy does not have to be aware of the AuthConfig
- **CON:** some change in Authorino still required to favour the metadata when present before the actual host info in the request

For use case 1 (wildcard domain), implementation is straightforward with either of the methods tried in the 2nd approach, as the host name to pass in the metadata would always be the base host name, e.g. `pets.com`.

For use case 2 (path-based routing), using a Lua script would likely be the only option to set the (fake) subdomain built out from the path, as both `context_extensions` ext-authz route-based config and the Set-Metadata filter only accept static constant strings in the config.

### Other approaches

With more changes involved in Authorino, possibly breaking _O(1)_ lookup complexity, but also relying less (or even nothing) on tweaking the Envoy config, other approaches still to explore include:
- Changing the cache data structure from being a map to become a lookup tree that evaluates more complex rules
- Allowing the same host to be added multiple times in the AuthConfig cache and implement a retry that moves the cursor to a subsequent host match when a previous one fails in the [`when` conditions](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#common-feature-conditions-when) –– It solves for path-based lookup (use-case 2), but not for the wildcard domains one (use-case 1).

I'll continue with the investigation.
