### ISSUE TITLE
Envoy Dynamic Metadata breaks with simple JSON values

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#232]
Setting Envoy dynamic metadata from a dynamic JSON, to be generated by Authorino in the response phase, fails when at least one of the properties of the JSON is given a static simple value, as opposed to a valued fetched from the Authorization JSON.

E.g.

```yaml
# fails
 response:
  - name: rate-limit
    wrapper: envoyDynamicMetadata
    wrapperKey: ext_auth_data
    json:
      properties:
      - name: username
        valueFrom:
          authJSON: auth.identity.metadata.annotations.auth-data\/username
      - name: group
        value: foo
```

```yaml
# does not fail
 response:
  - name: rate-limit
    wrapper: envoyDynamicMetadata
    wrapperKey: ext_auth_data
    json:
      properties:
      - name: username
        valueFrom:
          authJSON: auth.identity.metadata.annotations.auth-data\/username
      - name: group
        valueFrom:
          authJSON: "{missing}foo"
```

The error spotted in the logs is:

```
error":"proto: invalid type: runtime.RawExtension
```

Stacktrace:

```
github.com/kuadrant/authorino/pkg/service.(*AuthService).Check
	/workspace/pkg/service/auth.go:88
github.com/envoyproxy/go-control-plane/envoy/service/auth/v3._Authorization_Check_Handler.func1
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.1/envoy/service/auth/v3/external_auth.pb.go:700
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/envoyproxy/go-control-plane/envoy/service/auth/v3._Authorization_Check_Handler
	/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.1/envoy/service/auth/v3/external_auth.pb.go:702
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282
google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921
```

**Reproduce it**

Define an AuthConfig with dynamic JSON response wrapped for Envoy Dynamic Metadata, and define a property with simple static value.

**Expected behavior**

Generate the Envoy Dynamic Metadata containing the static value defined.

**Environment:**
- Authorino version: v0.7.0

**Additional context**

Root cause of the problem must be the `runtime.RawExtension` value carried as the empty interface value of the source map to the generate the dynamic metadata. See:

(defined as RawExtension in the AuthConfig)
https://github.com/Kuadrant/authorino/blob/a9f4882cc36f8b7d0f95b03aac6bfd937e1f2995/api/v1beta1/auth_config_types.go#L490

(carried to internal `Static: interface{}` as-is)
https://github.com/Kuadrant/authorino/blob/a9f4882cc36f8b7d0f95b03aac6bfd937e1f2995/controllers/auth_config_controller.go#L142

(also returned as-is when requested to build the map of dynamic metadata to generate)
https://github.com/Kuadrant/authorino/blob/a9f4882cc36f8b7d0f95b03aac6bfd937e1f2995/pkg/common/json.go#L60

(attempted to be transformed into the expected type of struct)
https://github.com/Kuadrant/authorino/blob/a9f4882cc36f8b7d0f95b03aac6bfd937e1f2995/pkg/service/auth.go#L95

(breaks in the golang lib used to do the transformation)
https://github.com/protocolbuffers/protobuf-go/blob/d77bd4b022342d35babe3feac256c24dd7013669/types/known/structpb/struct.pb.go#L359
