### ISSUE TITLE
Escaping characters in string templates

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#249]
Authorino fails to skip the escaping character (`/`) to the output of resolved string templates (i.e. strings that mix dynamic authorization JSON paths within static string values). This makes impossible to template valid JSON objects containing dynamic values, for example.

**Steps to reproduce**

1. Deploy Authorino
2. Create an AuthConfig containing the following `denyWith` config:
    ```yaml
    denyWith:
      unauthenticated:
        headers:
        - name: x-content-type
          value: application/json
        body:
          valueFrom:
            authJSON: |
              \{"request_path":"{context.request.http.path}"\}
    ```
3. Send a request to a `/hello` path of the protected API that would result in a `401 Unauthorized` response status
4. Verify that the actual body of the message returned is
    ```
    \{"request_path":"/hello"\}
    ```
    instead of
    ```json
    {"request_path":"/hello"}
    ```

**Expected behavior**

Escaping characters skipped in the output. I.e., for the example above, the body of the HTTP response should be:

```json
{"request_path":"/hello"}
```
