### ISSUE TITLE
dex example available

### ISSUE THREAD

**Issue by OperationalDev** [Kuadrant/authorino#257]
Is there an example of how to use oidc with dex? I see there is a dex setup in the e2e tests and authorino-examples repo, but it doesn't look like it's ever used.

**Comment by guicassolato** [comment]
@OperationalDev, we used to have a tutorial based on dex in the main repo, but it was removed. However, setting up Authorino to validate JWTs from a dex server is simple. It should be no different than with Keycloak really (at least from the perspective of writing the AuthConfig). Something like the following will do:

```yaml
spec:
  identity:
  - name: dex
    oidc:
      endpoint: http://dex:5556
```

The [Kuadrant/authorino-examples](https://github.com/Kuadrant/authorino-examples) repo still includes manifests to deploy a sample dex server pre-configured with a couple static clients and one user: https://github.com/Kuadrant/authorino-examples/tree/f6bf72d122e3e7a0b1d9e29bb28e1da51e4518b1#dex

This repo also includes another app, called [Talker Web](https://github.com/Kuadrant/authorino-examples/tree/f6bf72d122e3e7a0b1d9e29bb28e1da51e4518b1#talker-web). This is a webapp that implements OAuth Authorization Code flow with the dex server from above, and consumes the already known [Talker API](https://github.com/Kuadrant/authorino-examples#talker-api) we use in pretty much all examples of Authorino.

The sample Envoy configs included in Kuadrant/authorino-examples serve the Talker Web app on requests to `/web`.

So, say you follow steps 1-5 of Authorino's [OIDC/JWT authentication user guide](https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/oidc-jwt-authentication.md), skipping the step to deploy Keycloak. You can then:

1. Deploy dex:

```sh
kubectl -n authorino apply -f https://raw.githubusercontent.com/Kuadrant/authorino-examples/main/dex/dex-deploy.yaml
kubectl -n authorino wait --timeout=300s --for=condition=Available deployments --all
kubectl -n authorino port-forward deployment/dex 5556:5556 &
```

2. Deploy the Talker Web app:

```sh
kubectl -n authorino apply -f https://raw.githubusercontent.com/Kuadrant/authorino-examples/main/talker-web/talker-web-deploy.yaml
echo "127.0.0.1 dex" >> /etc/hosts # needed because the webapp is hardcoded to call dex on this host name
```

3. Create an AuthConfig as follows:
```yaml
kubectl -n authorino apply -f -<<EOF
apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
  - talker-api-authorino.127.0.0.1.nip.io
  identity:
  - name: dex
    oidc:
      endpoint: http://dex:5556
    credentials:
      in: cookie
      keySelector: ACCESS-TOKEN
EOF
```

And you should then be able to access http://talker-api-authorino.127.0.0.1.nip.io:8000/web on the web browser.

Click 'Login' and authenticate with:
- **Username:** marta@localhost
- **Password:** password
