### ISSUE TITLE
Nested dynamic parameters in the body of HTTP external metadata POST requests

### ISSUE THREAD

**Issue by OperationalDev** [Kuadrant/authorino#271]
### Feature Request/How to

It would be nice if when retrieving metadata, we could do an HTTP post with nested dynamic data.

e.g. If we want to post the following JSON

```
{
  "request": {
    "key1": {
      "key2": {
        "key3": "192.168.0.10"
      }
    }
  }
}
```
Our metadata config would look like this and it works great:

```
metadata:
  - name: echo-api-post-json
    http:
      endpoint: http://talker-api.authorino.svc.cluster.local:3000/metadata?encoding=json
      method: POST
      contentType: application/json
      bodyParameters:
        - name: original_path
          valueFrom:
            authJSON: context.request.http.headers.x-forwarded-for
        - name: request
           value: 
             key1:
               key2:
                 key3: 192.168.0.10
```
However, how would we go about making "192.168.0.1" piece dynamic? e.g.
```
metadata:
  - name: echo-api-post-json
    http:
      endpoint: http://talker-api.authorino.svc.cluster.local:3000/metadata?encoding=json
      method: POST
      contentType: application/json
      bodyParameters:
        - name: original_path
          valueFrom:
            authJSON: context.request.http.headers.x-forwarded-for
        - name: request
           value: 
             key1:
               key2:
                 key3: 
                 valueFrom:
                   authJSON: context.request.http.headers.x-forwarded-for
```

Is this currently possible/supported?

**Comment by guicassolato** [comment]
@OperationalDev, have you tried [interpolated JSON paths](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#interpolation)?

Please, see if the following works for you:

```yaml
metadata:
  - name: echo-api-post-json
    http:
      endpoint: http://talker-api.authorino.svc.cluster.local:3000/metadata?encoding=json
      method: POST
      contentType: application/json
      bodyParameters:
        - name: original_path
          valueFrom:
            authJSON: context.request.http.headers.x-forwarded-for
        - name: request
           valueFrom:
             authJSON: |
               \{ "key1": \{ "key2": \{ "key3": {context.request.http.headers.x-forwarded-for} \} \} \}
```
