### ISSUE TITLE
Integration with Authzed

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#372]
Built-in integration with [Authzed](https://authzed.com/).

**API:**

```yaml
spec:
  identity:
    - name: jwt
      oidc:
        endpoint: https://sso-server
  authorization:
    - name: authzed
      authzed:
        endpoint: https://authzed:50051
        insecure: true
        tokenSecretRef:
          name: authzed
          key: bearer-token
        subject:
          valueFrom:
            authJSON: auth.identity.sub
        permission:
          value: read
        resource:
          valueFrom:
            authJSON: context.request.http.path
      cache:
        key:
          valueFrom:
            authJSON: "{auth.identity.sub}#{context.request.http.path.@base64:encode}"
        ttl: 60
```

**Implementation:**

https://github.com/thomasdarimont/custom-opa-spicedb/blob/8fb0400ab04888d4a4e7367fb9e7f63b8cf0ff6f/builtins/check_permission.go#L72-L87
