### ISSUE TITLE
Plain/text responses

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#392]
RFE: add support for plain/text response method.

In the case of content wrapped for request header injection, currently one can do:
```
x-auth-data: "{\"username\":\"john\"}"
```

but not:
```
x-username: john
```

This is a request to enable the latter.

<br/>

A few alternatives considered for the API:

**OPTION 1 - new response method: `plain`**

```yaml
  response:
  - name: x-auth-service
    plain:
      value: Authorino
  - name: x-username
    plain:
      valueFrom: { authJSON: auth.identity.username }
```

**OPTION 2 - enhance the existing [`json`](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#json-injection-responsejson) response method**

```yaml
  response:
  - name: x-dynamic-obj
    json:
      object: # deprecates: `properties`
      - name: auth-service
        value: Authorino
      - name: username
        valueFrom: { authJSON: auth.identity.username }
  - name: x-dyamic-arr
    json:
      array:
      - value: Authorino
      - valueFrom: { authJSON: auth.identity.username }
  - name: x-auth-service
    json:
      value: Authorino
  - name: x-username
    json:
      valueFrom: { authJSON: auth.identity.username }
```

The spec of `spec.response.json` would enforce one of: `object`, `array`, `value`, `valueFrom`, with some overlap between `valueFrom` and all the others due to the possibility of doing [interpolations](https://github.com/Kuadrant/authorino/blob/main/docs/features.md#interpolation).

<br/>

Support for interpolations in `valueFrom.authJSON` effectively makes **OPTION 1** a generalization for all other options. By adding either `response.plain.valueFrom` or `response.json.valueFrom`, other options would only be kept in the API for the user's convenience, so things such as the following could be more easily achieved, e.g., using `response.json.object`:

```yaml
  response:
  - name: x-dynamic-json
    plain:
      valueFrom:
        authJSON: |
          \{"auth-service":"Authorino","username":"{authJSON: auth.identity.username}"\}
```
