### ISSUE TITLE
Do not overwrite identity extended properties

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/authorino#395]
RFE: option to decide when to overwrite an existing extended property from an identity object.

Currently, Authorino does not check on the existence of the property in the identity object and simply extends the object with the new value, occasionally overwriting an existing one. 

**Example of use case where this is problematic:**

Given the following identity config:

```yaml
identity:
- name: k8s-tokens
  kubernetes: {}
  extendedProperties:
  - name: username
    valueFrom:
      authJSON: auth.identity.sub
```

For Kubernetes opaque tokens whose resolved identity object equals the `status.user` info from the TokenReview response, the `username` claim will be replaced with a `null` value.

This issue was described as well as part of #394.

**API implementation:**

```yaml
identity:
- name: k8s-tokens
  kubernetes: {}
  extendedProperties:
  - name: username
    valueFrom:
      authJSON: auth.identity.sub
    overwrite: true # default: false
```
