### ISSUE TITLE
AuthPolicy missing overwrite key in extendedProperties

### ISSUE THREAD

**Issue by azgabur** [Kuadrant/authorino#411]
**Describe the bug**

While testing the new _overwrite_ functionality in extendedProperties #395 I noticed the overwrite key missing when trying to append it in AuthPolicy configuration. This results in the default `false` value being always applied.

**Help us Reproduce it**

Create new AuthPolicy in _Authorino_ namespace with any Identity verification adding extendedProperty with _overwrite_ value set to `true`.
Example:

```yaml
spec:
  authScheme:
    identity:
      - name: api_key
        apiKey:
          selector:
            matchLabels:
              group: label
        credentials:
          in: authorization_header
          keySelector: APIKEY
        extendedProperties:
          - name: data
            overwrite: true  # will disappear 
            value:
              api_key: text
```

**Expected behavior**

- The _overwrite_ value not disappearing in AuthPolicy
- Correct _overwrite_ value in generated AuthConfig and not always `false`

**Environment:**
-  Openshift 4.12.17
- Using `quay.io/kuadrant/kuadrant-operator-catalog:84d931147029ed1da4702b98b60dd0d4f114d0b6` operator 

**Additional context**

When changing/appending the _overwrite_ value in AuthConfig it works as expected. The problem is in AuthPolicy.
