### ISSUE TITLE
Allow for dynamic unauthenticated/unauthorized responses

### ISSUE THREAD

**Issue by OperationalDev** [Kuadrant/authorino#491]
**Current Issue**

We have some services behind an authconfig that are used by both systems and users from a browser. When a user tries to access the services from their browser and is unauthenticated, we return a 302, similar to the example here https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/deny-with-redirect-to-login.md

However when a system makes a call to the service, we don't want to give them back a 302, we want to be able to give them back a 401 instead. 

At the moment we have this working by using response.unauthenticated to always return a 401 and then using response.unauthorized to return a 302 and making user requests skip response.unauthenticated which works well, but it makes it difficult to add authorization as well for other use cases.

**Possible solutions**

Having multiple response.unauthenticated/unauthenticated responses (similar to how we can have multiple authentication types) and then using priority and when to determine which ones are invoked.
```
apiVersion: authorino.kuadrant.io/v1beta2
kind: AuthConfig
metadata:
  name: matrix-quotes-protection
spec:
  hosts:
  - matrix-quotes.127.0.0.1.nip.io
  authentication:
    "browser-users":
      apiKey:
        selector:
          matchLabels:
            group: users
      credentials:
        cookie:
          name: TOKEN
    "http-basic-auth":
      apiKey:
        selector:
          matchLabels:
            group: users
      credentials:
        authorizationHeader:
          prefix: Basic
  response:
    unauthenticated:
    - name: unauthenticated-browser
      code: 302
      priority: 0
      headers:
        "Location":
          selector: "http://matrix-quotes.127.0.0.1.nip.io:8000/login.html?redirect_to={request.path}"
      when:
      - selector: context.request.http.headers.user-agent
        operator: matches
        value: "Mozilla"
    - name: unauthenticated-system
      code: 401
      priority: 1
```

**Comment by guicassolato** [comment]
Hi @OperationalDev. Thanks for suggesting this feature. It sounds an interesting use case to cover.

I imagine that, in case multiple custom responses match (same priority, both blocks of `when` conditions evaluating to true), then whichever config happens to evaluate first wins, similarly to how authentication and authorization phases work already?

**Comment by OperationalDev** [comment]
TBH I hadn't thought about that use case as I tend to always use priority, but to keep things consistent, I think it would make sense to make it behave the same way.

**Comment by Aman-Cool** [comment]
Been in this path recently on the `jwt.issuer`/`aud` work, where a lot of the point was getting
a rejection to come out of the authentication phase so it lands on `response.unauthenticated`
as a 401 rather than a 403. Which is what sent me here: `DenyWithSpec` is the only config block
in the spec that doesn't embed `CommonEvaluatorSpec`, so it's the one place with no `when` and
no `priority`. One denial shape per outcome, and the `code` is a static int.

The values in there are already dynamic; `message`, `headers` and `body` all resolve against
the authorization JSON in `customizeDenyWith()`. It's only the *selection* that's fixed. Was
that deliberate? `response.success.headers` gets `when` and `priority` for free off
`CommonEvaluatorSpec`, so the asymmetry may just be that nobody needed it yet.

@OperationalDev's workaround above works, but it costs more than it looks: letting browsers
through as anonymous so their denial comes out of `unauthorized` spends the `unauthorized`
response on user-agent sniffing, so the day you add a real authorization policy a genuine 403
hands the browser a login redirect. And the codes stop meaning what the logs and metrics say.

What I'd suggest: leave `unauthenticated`/`unauthorized` exactly as they are, as the default,
and hang an optional `overrides` map off them carrying `when` + `priority`, same as everywhere
else:

```yaml
response:
  unauthenticated:
    code: 401                                  # the default, when no override matches
    message:
      value: "Authentication required"
    overrides:
      "first":
        priority: 0
        when:
        - predicate: '"x-example" in request.headers && request.headers["x-example"] == "a"'
        code: 302
        headers:
          "Location":
            expression: '"https://example.com/login?redirect_to=" + request.path'
      "second":
        priority: 1
        when:
        - predicate: request.path.startsWith("/example")
        message:                               # code not set, falls through to 401
          value: "Credentials required for this path"
```

First override that matches wins, ordered by priority; fields it sets override the base, the
rest fall through. No overrides → byte-for-byte what happens today. Purely additive to
`DenyWithSpec`, so no v1beta4 and no conversion webhook. I'd avoid turning the field into a
list as originally sketched.., same expressiveness, but it breaks every existing AuthConfig.

Implementation lands where you'd expect and is small. `buildAuthorinoDenyWithValues()` already
has `authConfig` in hand, so `buildPredicates()` gives me `when` for free (CEL, pattern-matching
and `patternRef`), compiled at reconcile time; `customizeDenyWith()` picks the winner before
applying. A bad predicate fails translation and surfaces as `InvalidResource` rather than at
request time; one that errors at *request* time (the `no such key` case in #505) I'd treat as
no-match and fall through, same as `evaluateConditions()` does today — safe to do here in a way
it isn't in #505, since falling through lands you on the base denial rather than on an allow.
Hence the `in` guard in the example.

Two calls I'd want before writing it:

1. **Ties.** @guicassolato asked above whether same-priority matches should be "whichever
   evaluates first", like the phases. I'd rather sort by (priority, name) and be deterministic.
   The phases are only nondeterministic because they run concurrently; this is a sequential
   first-match pick, and a denial code that differs between replicas is miserable to debug.
2. **Merge vs. replace.** I've assumed the winning override merges over the base, which falls
   out of the existing `if Code != 0` / `!= nil` checks. Full replacement is simpler to
   document if you'd prefer that.

Happy to pick this up and open the PR if there's appetite for it.
