### ISSUE TITLE
Success response headers are not added to the response

### ISSUE THREAD

**Issue by averevki** [Kuadrant/authorino#515]
**Describe the bug**
Since kuadrant-operator-catalog nightly builds from `28-29.01.25` our tests that should return custom success response headers started failing. They don't add these headers into the response anymore. Here is the [most simple test](https://github.com/Kuadrant/testsuite/blob/4b95ca14fe0ee697f8f0e615adbb0be21a49071d/testsuite/tests/singlecluster/authorino/response/test_simple_response.py#L19) for responses we got that is failing with `AssertionError: Header from response (Header) is missing; assert None is not None`

We were experiencing the same failures a few months ago, which ended up being a bug inside the wasm-shim, and was fixed by [this](https://github.com/Kuadrant/wasm-shim/pull/143) PR.

**Help us Reproduce it**

AuthPolicy:
```yaml
spec:
  rules:
    authentication:
      default:
        credentials:
          authorizationHeader:
            prefix: Bearer
        jwt:
          issuerUrl: 'http://1.2.3.4:8080/realms/realm-averevki--eyt7'
          ttl: 0
        metrics: false
        priority: 0
    response:
      success:
        headers:
          header:
            json:
              properties:
                anything:
                  value: one
            metrics: false
            priority: 0
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-averevki--obnu
```
<details>
<summary>Gateway</summary>

```yaml
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: '*.apps.kua.redhat.com'
      name: api
      port: 80
      protocol: HTTP
```
</details>

<details>
<summary>HTTPRoute</summary>

```yaml
spec:
  hostnames:
    - hostname-averevki--nbep-kuadrant.apps.kua.redhat.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gw-averevki--ljiu
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: httpbin-averevki--ihex
          namespace: kuadrant
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```
</details>

**Expected behavior**

Return headers I specify inside AuthPolicy with a successful response

**Environment (please complete the following information):**

kuadrant-operator image: `nightly-04-02-2025`
authorino-operator image: `e1dc399c6bcb2fb6d28b2f3e94ce49bb5b63e06c`
authorino image: `b2bde91bfc64b1d140f740069ba36ce81a3f3349`
wasm-shim image: `751af05ea5e6c440d6254480d669bc5861f457eb`
